version: "3.7"

services:
  node-red:
    image: nodered/node-red:latest
    ports:
      - "1880:1880"
    volumes:
      - ./data/node-red:/data
    #      - ./data/modules:/modules # For modules generated separately under /modules,
    #                                  to install modules run this command inside the container:
    #                                  cd /data; npm install /modules/package-name
    depends_on:
      - test-app
  test-app:
    build: ./test-api-docker
    ports:
      - "5000:5000"
    volumes:
      - ./data/node-red/node_modules:/modules # Generate the modules directly in node-red's node_modules
      #      - ./data/modules:/modules # Generate the modules separately under /modules
      - ./test-api-docker/test_api_app.py:/app/test_api_app.py # include the app file to debug changes to the app
#      - ../nodered_forge:/app/nodered_forge # include the module files to debug changes to the module